import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-lowest": "#090f11",
        "bg-surface": "#131826",
        "accent-gas": "#F2622E",
        "outline-variant": "#3d484e",
        "on-secondary-fixed-variant": "#5e4200",
        "tertiary-fixed-dim": "#ffb77a",
        "on-error": "#690005",
        "primary-container": "#3ec6f0",
        "surface-container-low": "#171c1f",
        "on-secondary": "#422d00",
        "on-surface-variant": "#bcc8cf",
        "surface-container-high": "#252b2d",
        "accent-presupuesto": "#3EC6F0",
        "text-primary": "#E7ECF5",
        "on-primary-container": "#004f64",
        "text-secondary": "#8792A8",
        "surface": "#0f1417",
        "secondary-fixed": "#ffdea8",
        "on-tertiary-fixed": "#2e1500",
        "on-secondary-container": "#392600",
        "surface-bright": "#343a3d",
        "on-tertiary-fixed-variant": "#6d3a00",
        "accent-crisis": "#FF3B4E",
        "on-background": "#dee3e6",
        "tertiary-container": "#ffa24a",
        "error": "#ffb4ab",
        "surface-container-highest": "#303638",
        "tertiary-fixed": "#ffdcc2",
        "on-secondary-fixed": "#271900",
        "surface-dim": "#0f1417",
        "on-primary-fixed": "#001f29",
        "on-error-container": "#ffdad6",
        "accent-eficiencia": "#3ECF8E",
        "outline": "#879398",
        "on-surface": "#dee3e6",
        "background": "#0f1417",
        "on-tertiary-container": "#6f3b00",
        "surface-variant": "#303638",
        "primary": "#8bdfff",
        "accent-electricidad": "#F5B942",
        "on-primary": "#003544",
        "surface-container": "#1b2023",
        "inverse-on-surface": "#2c3134",
        "border-subtle": "#232B3D",
        "secondary-container": "#bc8708",
        "secondary": "#f9bc45",
        "error-container": "#93000a",
        "secondary-fixed-dim": "#f9bc45",
        "tertiary": "#ffc89c",
        "primary-fixed-dim": "#55d5ff",
        "primary-fixed": "#b9eaff",
        "bg-primary": "#0A0E17",
        "surface-tint": "#55d5ff",
        "inverse-surface": "#dee3e6",
        "inverse-primary": "#006780",
        "on-tertiary": "#4c2700",
        "on-primary-fixed-variant": "#004d61"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "space-sm": "1rem",
        "space-lg": "2rem",
        "space-md": "1.5rem",
        "gutter": "1rem",
        "space-xl": "3rem",
        "space-xs": "0.5rem",
        "gutter-desktop": "1.5rem",
        "margin": "1rem",
        "margin-desktop": "2rem"
      },
      fontFamily: {
        "body-sm": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-xl": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "headline-xl-mobile": ["Inter", "sans-serif"],
        "label-lg": ["JetBrains Mono", "monospace"],
        "label-md": ["JetBrains Mono", "monospace"],
        "label-sm": ["JetBrains Mono", "monospace"],
        "metric-display": ["JetBrains Mono", "monospace"],
        "metric-display-mobile": ["JetBrains Mono", "monospace"]
      },
      fontSize: {
        "body-sm": ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-xl": ["36px", { lineHeight: "44px", fontWeight: "700" }],
        "headline-lg": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-xl-mobile": ["28px", { lineHeight: "36px", fontWeight: "700" }],
        "label-lg": ["14px", { lineHeight: "20px", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "label-sm": ["10px", { lineHeight: "14px", fontWeight: "500" }],
        "metric-display": ["32px", { lineHeight: "40px", fontWeight: "700" }],
        "metric-display-mobile": ["24px", { lineHeight: "32px", fontWeight: "700" }]
      }
    }
  },
  plugins: [],
};

export default config;
