import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        surface: "#12121d",
        "surface-dim": "#12121d",
        "surface-bright": "#393844",
        "surface-container-lowest": "#0d0d17",
        "surface-container-low": "#1b1b25",
        "surface-container": "#1f1f2a",
        "surface-container-high": "#292934",
        "surface-container-highest": "#34343f",
        "surface-variant": "#34343f",
        "on-surface": "#e4e1f0",
        "on-surface-variant": "#bacbb8",
        outline: "#859584",
        "outline-variant": "#3c4a3c",
        primary: "#b7ffbe",
        "primary-fixed": "#66ff8e",
        "primary-fixed-dim": "#09e46b",
        "primary-container": "#2bf075",
        "on-primary": "#003915",
        "on-primary-container": "#00682d",
        secondary: "#e6feff",
        "secondary-fixed": "#63f7ff",
        "secondary-fixed-dim": "#00dce5",
        "secondary-container": "#00f4fe",
        "on-secondary": "#003739",
        "on-secondary-container": "#006c71",
        tertiary: "#ffe8ec",
        "tertiary-fixed": "#ffd9e1",
        "tertiary-fixed-dim": "#ffb1c4",
        "tertiary-container": "#ffc1cf",
        "on-tertiary": "#65002e",
        "on-tertiary-container": "#b20056",
        error: "#ffb4ab",
        "error-container": "#93000a",
        "on-error": "#690005",
        "on-error-container": "#ffdad6",
        "neon-green": "#2bf075",
        "neon-cyan": "#00f5ff",
        "neon-magenta": "#ff007f",
        "meltdown-crimson": "#ff1b3a",
        "warning-amber": "#ffb000",
      },
      fontFamily: {
        mono: ["Space Mono", "JetBrains Mono", "Courier New", "monospace"],
        headline: ["Space Mono", "monospace"],
        data: ["JetBrains Mono", "monospace"],
      },
      spacing: {
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2.5rem",
        gutter: "1rem",
        "gutter-desktop": "1.5rem",
      },
      keyframes: {
        jitter: {
          "0%, 100%": { transform: "translate(0, 0)" },
          "20%": { transform: "translate(-2px, 2px)" },
          "40%": { transform: "translate(-1px, -2px)" },
          "60%": { transform: "translate(2px, 1px)" },
          "80%": { transform: "translate(1px, -1px)" },
        },
        violentJitter: {
          "0%, 100%": { transform: "translate(0, 0) rotate(0deg)" },
          "10%": { transform: "translate(-4px, 3px) rotate(-0.5deg)" },
          "30%": { transform: "translate(4px, -3px) rotate(0.5deg)" },
          "50%": { transform: "translate(-3px, -4px) rotate(-1deg)" },
          "70%": { transform: "translate(4px, 2px) rotate(1deg)" },
          "90%": { transform: "translate(-2px, 4px) rotate(-0.5deg)" },
        },
        scanline: {
          "0%": { transform: "translateY(-100%)" },
          "100%": { transform: "translateY(100%)" },
        },
        glitchText: {
          "0%": { textShadow: "2px 0 #00f5ff, -2px 0 #ff1b3a" },
          "25%": { textShadow: "-2px 0 #00f5ff, 2px 0 #ff1b3a" },
          "50%": { textShadow: "1px -1px #00f5ff, -1px 1px #ff1b3a" },
          "75%": { textShadow: "-2px -1px #00f5ff, 2px 1px #ff1b3a" },
          "100%": { textShadow: "2px 0 #00f5ff, -2px 0 #ff1b3a" },
        },
        flicker: {
          "0%, 100%": { opacity: "1" },
          "41.99%": { opacity: "1" },
          "42%": { opacity: "0.8" },
          "43%": { opacity: "1" },
          "45%": { opacity: "0.3" },
          "46%": { opacity: "1" },
        },
      },
      animation: {
        jitter: "jitter 0.2s ease-in-out infinite",
        "violent-jitter": "violentJitter 0.15s ease-in-out infinite",
        scanline: "scanline 8s linear infinite",
        "glitch-text": "glitchText 0.3s ease-in-out infinite",
        flicker: "flicker 2s infinite",
      },
    },
  },
  plugins: [],
};

export default config;
